# Generated by Django 6.0 on 2025-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('short_description', models.CharField(max_length=64, verbose_name='Сокращенное описание')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('duration_minutes', models.SmallIntegerField(verbose_name='Продолжительность')),
                ('image', models.ImageField(blank=True, upload_to='service_images', verbose_name='Фото')),
                ('is_provided', models.BooleanField(verbose_name='Предоставляется')),
                ('is_key', models.BooleanField(verbose_name='Ключевая')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
