# Generated by Django 6.0 on 2025-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('duration_minutes', models.SmallIntegerField(verbose_name='Продолжительность')),
                ('is_provided', models.BooleanField(verbose_name='Предоставляется')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
