# Generated by Django 6.0 on 2025-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('short_text', models.TextField(max_length=64, verbose_name='Сокращенное содержание')),
                ('text', models.TextField(max_length=256, verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, upload_to='service_images', verbose_name='Фото')),
                ('is_published', models.BooleanField(verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
